const q=$json.query||{};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guayaquil',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const start=String(q.start||'2026-09-01'),end=String(q.end||today);
const valid=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
if(!valid(start)||!valid(end)||start>end||end>today||(Date.parse(end)-Date.parse(start))/86400000>=366)throw new Error('Invalid date range');
const markets=q.view==='markets',trends=q.view==='country_daily',diagnostics=q.view==='landing_diagnostics';
const dimensionFilter={notExpression:{andGroup:{expressions:[{filter:{fieldName:'country',stringFilter:{matchType:'EXACT',value:'United States',caseSensitive:false}}},{filter:{fieldName:'city',stringFilter:{matchType:'EXACT',value:'Cutler Bay',caseSensitive:false}}}]}}};
const publicHostFilter={filter:{fieldName:'hostName',inListFilter:{values:['mindobirdwatching.com','www.mindobirdwatching.com'],caseSensitive:false}}};
const websiteFilter={andGroup:{expressions:[dimensionFilter,publicHostFilter]}};
const metrics=['totalUsers','sessions','engagedSessions','engagementRate'].map(name=>({name}));
const labels=diagnostics?['not_set_events']:trends?['country_daily']:markets?['countries','cities','daily','sources','landing_pages']:['summary','acquisition','countries','devices','landing_pages'];
const dimensions=diagnostics?[['date','eventName','pagePath','hostName']]:trends?[['country','date']]:markets?[['country'],['country','region','city','cityId'],['country','region','city','cityId','date'],['country','region','city','cityId','sessionSourceMedium','sessionCampaignName'],['country','region','city','cityId','landingPage']]:[[],['sessionSourceMedium','sessionCampaignName'],['country'],['deviceCategory'],['landingPage']];
return [{json:{start,end,labels,schema_version:markets||trends||diagnostics?2:1,exclusions:['Cutler Bay, United States','Non-public hostnames (admin, staging and other sites)'],body:{requests:dimensions.map(d=>({dateRanges:[{startDate:start,endDate:end}],dimensions:d.map(name=>({name})),dimensionFilter:diagnostics?{andGroup:{expressions:[dimensionFilter,{filter:{fieldName:'landingPage',stringFilter:{matchType:'EXACT',value:'(not set)'}}}]}}:websiteFilter,metrics:diagnostics?[{name:'eventCount'}]:metrics,limit:markets||trends?'100000':'10000',orderBys:[{metric:{metricName:diagnostics?'eventCount':'sessions'},desc:true}]}))}}}];
