import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const context={Intl,Date};vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('../admin/assets/js/crm-review.js',import.meta.url),'utf8'),context);const review=context.MbwCrmReview;
const record={inquiry_id:'qa',full_name:'QA Guest',assigned_to:'JPG',status:'booked',requested_date:'2099-10-12',guest_count:'2',quote_status:'accepted',payment_status:'paid'};
const service={id:'primary',label:'Bird tour',product_selected:'MBW004 - Jewels',service_type:'Birdwatching',status:'booked',date:'2099-10-12',guests:'2'};
const assignment={inquiry_id:'qa',product_selected:service.product_selected,service_date:service.date,provider_name:'QA Guide',provider_informed:'Yes',assignment_status:'confirmed'};
const fixture=()=>({record:{...record},services:[{...service}],assignments:[{...assignment}],confirmation:{missing:[],message:'QA draft'},reminder:{kind:'scheduled',date:'2099-10-10',tourDate:'2099-10-12'},delivery:{status:'pending'},operationsLoaded:true,today:'2099-10-09'});
test('read-only readiness models preserve source data and produce a ready booked reminder',()=>{const input=fixture(),before=JSON.stringify(input);const model=review.build(input);assert.equal(model.ready,true);assert.equal(model.reviewState,'Details complete');assert.equal(JSON.stringify(input),before);assert.equal(model.suggestion.date,'2099-10-10');});
test('readiness blocks missing, pending, cancelled, wrong-date and unrelated assignments',()=>{for(const patch of [{provider_name:''},{assignment_status:'pending'},{assignment_status:'cancelled'},{service_date:'2099-10-13'},{inquiry_id:'other'}]){const input=fixture();Object.assign(input.assignments[0],patch);const model=review.build(input);assert.equal(model.ready,false);assert.match(model.missing.join(';'),/Confirm guide assignment/);}});
test('transport requires a confirmed informed driver and flexible activities do not need a guide',()=>{const input=fixture();input.services=[{...service,product_selected:'TRANS03 - Round trip',service_type:'Transportation',label:'Transport'}];input.assignments=[];assert.match(review.build(input).missing.join(';'),/driver/);input.services=[{...service,product_selected:'ACT017 - Biking',service_type:'Activity'}];assert.equal(review.build(input).ready,true);});
test('every service is checked and provider informed is required',()=>{const input=fixture();input.services.push({...service,id:'night',product_selected:'MBW016 - Night Walk',service_type:'Activity',label:'Night walk'});const model=review.build(input);assert.equal(model.ready,false);assert.match(model.missing.join(';'),/Night walk: Confirm guide/);input.services.pop();input.assignments[0].provider_informed='No';assert.match(review.build(input).missing.join(';'),/Notify provider/);});
test('unavailable operations data never produces ready or hides reminders as sent',()=>{const input=fixture();input.operationsLoaded=false;input.delivery.status='sent';const model=review.build(input);assert.equal(model.ready,false);assert.equal(model.sent,false);assert.equal(model.reviewState,'Data not verified');assert.equal(review.queue([{model,record}]).length,1);});
test('queue excludes closed, archived, past and unchanged sent bookings',()=>{const items=[];for(const status of ['completed','cancelled','did_not_book','duplicate']){const input=fixture();input.record.status=status;items.push({model:review.build(input),record:input.record});}const past=fixture();past.reminder.kind='past';items.push({model:review.build(past),record:past.record});const sent=fixture();sent.delivery.status='sent';items.push({model:review.build(sent),record:sent.record});const archived=fixture();archived.record.is_archived='Yes';items.push({model:review.build(archived),record:archived.record});assert.equal(review.queue(items).length,0);});
test('rescheduling changes reminder without changing manual follow-up or input',()=>{const input=fixture();input.record.followup_date='2099-10-11';input.reminder={kind:'scheduled',date:'2099-10-18',tourDate:'2099-10-20'};const model=review.build(input);assert.equal(model.reminderDate,'2099-10-18');assert.equal(model.followupDate,'2099-10-11');assert.equal(input.record.followup_date,'2099-10-11');});
test('follow-up suggestions use recent contact, Ecuador dates, overdue review and closed exclusions',()=>{const sales={status:'quoted',quote_status:'sent',followup_date:'2099-10-15'};assert.equal(review.suggestion(sales,'2099-10-09',null,'2099-10-09T01:00:00Z').date,'2099-10-11');assert.equal(review.suggestion(sales,'2099-10-09',null,'2099-10-01').date,'2099-10-09');assert.equal(sales.followup_date,'2099-10-15');assert.equal(review.suggestion({...sales,status:'cancelled'},'2099-10-09'),null);});

test('services sort by date then time and urgency respects Ecuador day',()=>{const input=fixture();input.services=[{...input.services[0],date:'2099-10-13',start_time:'06:00'},{...input.services[0],date:'2099-10-12',start_time:'09:00'},{...input.services[0],date:'2099-10-12',start_time:'05:00'}];input.record={...input.record,followup_date:input.today};const before=JSON.stringify(input);const model=review.build(input);assert.deepEqual(model.services.map(s=>s.start),['05:00','09:00','06:00']);assert.equal(model.followupUrgency,'today');assert.equal(JSON.stringify(input),before);input.record.followup_date='2020-01-01';assert.equal(review.build(input).followupUrgency,'overdue');input.record.followup_date='';assert.equal(review.build(input).followupUrgency,'missing');});
