import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../admin/guest-crm/index.html',import.meta.url),'utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const CRM_API_DEFAULT'));
new Function(script);
const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{dataset:{},value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return[];}});return nodes.get(id);};
const context={URLSearchParams,URL,Date,Intl,console,setTimeout,clearTimeout,location:{search:'',hostname:'localhost'},localStorage:{getItem(){return null;},setItem(){}},document:{getElementById:node,addEventListener(){},querySelectorAll(){return [];}},window:{addEventListener(){},location:{search:''}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL("../admin/assets/js/crm-review.js",import.meta.url),"utf8"),context);
vm.runInContext(script.replace('    })();','    globalThis.qa={api,renderReview,reviewModel,setReviewVerified(value){reviewOperationsVerified=value;},productSchedule,serviceSchedule,normalizeTourItem,serializeTourItems,normalizeTourItems,inheritServiceDefaults,confirmationModel,quoteAcceptance,persistQuoteAcceptance,autoPriority,primaryTourItemFromForm,formRecord,renderInvoiceState,bookingReviewIssues,interactionDisplayNote,reminderDeliveryKey,reminderReadiness,reminderDeliveryState,renderActionCounts,preTourReminder,compareReminderDates,cache,saveInteraction,setMocks(mock){api=mock.api;loadGuestWorkspace=async()=>{};render=()=>{};saveLocalRecords=()=>{};showToast=mock.toast;upsert=record=>{state.records=state.records.map(r=>r.inquiry_id===record.inquiry_id?record:r);};clearInteractionForm=()=>{};},setReportRows(rows){filteredReportRows=()=>rows;},serviceVisual,productVisual,popularProductLabel,optionsHtml,calendarEntriesForRecord,reportServiceKey,serviceItemLabel,reportCsv,reportPlainText,followupEligible,isTripFollowup,compareFollowups,getFiltered,renderFollowupSummary,state,els};})();'),context);
const q=context.qa;for(const id of ['searchInput','inlineSearchInput','statusFilter','inlineStatusFilter','repFilter','inlineRepFilter','quoteFilter','paymentFilter','viewFilter','followupFilter','sortInput','sortDirectionInput','statFollowUp','reportRangeHint','reportTypeInput','reportStatusInput'])q.els[id]=node(id);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
const product='ACT017 - Mountain Biking';
const row={inquiry_id:'fixture-bike',full_name:'QA Guest',tour_type:'Birdwatching',tour_category:'Birdwatching',service_type:'Birdwatching',product_selected:'MBW005 - Dance of the Andean Cock-of-the-Rock',requested_date:'2099-10-08',followup_date:'2020-01-01',status:'booked',tour_items_json:JSON.stringify([{id:'1',tour:'Other Activity or Tour',product_selected:product,service_type:'Activity',date:'2099-10-08',guests:'1',status:'booked'}])};
test('additional biking uses its own product and remains an activity in reports',()=>{const entry=q.calendarEntriesForRecord(row)[0];assert.equal(entry.service_type,'Activity');assert.equal(q.serviceVisual(entry).icon,'🚵🏼');assert.equal(q.serviceVisual(entry).label,'Mountain biking');assert.equal(q.serviceVisual(entry).fullLabel,'Mountain Biking');assert.equal(q.reportServiceKey(entry),'other');assert.equal(q.serviceItemLabel(entry._calendar_item).label,'Mountain Biking');});
test('all catalog icons stay outside canonical option values and report names',()=>{for(const [code,icon] of [['MBW004','🐥'],['MBW005','🐓'],['MBW006','🦜'],['MBW016','🦉'],['ACT017','🚵🏼'],['ACCOM01','🏨'],['TRANS03','🚘'],['MBW007','🐦'],['OSO002','🐻']]){assert.equal(q.productVisual(code)[0],icon);const canonical=code+' - Example';assert.ok(q.popularProductLabel(canonical).startsWith(icon+' '));assert.match(q.optionsHtml([canonical],canonical),new RegExp('value="'+canonical+'"'));assert.doesNotMatch(q.serviceVisual({product_selected:canonical}).fullLabel,/\p{Extended_Pictographic}/u);}});
test('due counts use the same eligibility as the queue and sales/trip queues partition it',()=>{q.state.records=[row,{...row,inquiry_id:'sales',status:'quoted',tour_items_json:'',product_selected:'MBW006',payment_status:'unpaid'},{...row,inquiry_id:'past',requested_date:'2020-01-01',tour_items_json:''},{...row,inquiry_id:'closed',status:'completed'},{...row,inquiry_id:'archived',is_archived:'Yes'},{...row,inquiry_id:'today',followup_date:today}];q.els.viewFilter.value='followups';q.els.sortInput.value='followup_date';q.els.sortDirectionInput.value='asc';const all=q.getFiltered();assert.equal(all.length,3);q.renderFollowupSummary();assert.ok(q.els.statFollowUp.innerHTML.startsWith('3'));q.els.viewFilter.value='salesFollowups';assert.equal(q.getFiltered().length,1);q.els.viewFilter.value='tripFollowups';assert.equal(q.getFiltered().length,2);assert.equal(all.at(-1).inquiry_id,'today');});
test('missing next step identifies missing date or owner or purpose without closed rows',()=>{q.state.records=[{...row,assigned_to:'JPG',next_action:'Confirm pickup'},{...row,inquiry_id:'missing',followup_date:''},{...row,inquiry_id:'closed',status:'completed'}];q.els.viewFilter.value='missingNextStep';assert.deepEqual(Array.from(q.getFiltered(),r=>r.inquiry_id),['missing']);});

test('CSV and copied report text contain plain product names with no display emojis',()=>{const entry=q.calendarEntriesForRecord(row)[0];q.setReportRows([{...entry,_report_date:'2099-10-08'}]);q.els.reportTypeInput.value='all';q.els.reportStatusInput.value='all';for(const output of [q.reportCsv(),q.reportPlainText()]){assert.match(output,/Mountain Biking/);assert.doesNotMatch(output,/\p{Extended_Pictographic}/u);assert.doesNotMatch(output,/Birding/);}});
test('logging follow-up saves history before updating the date and safely reports partial failure',async()=>{q.cache();q.state.records=[row];q.state.selectedId=row.inquiry_id;Object.assign(q.els.interactionNote,{value:'Outcome: guest requested more time'});q.els.interactionOccurredAt.value='2026-10-06T09:00';q.els.interactionDirection.value='outgoing';q.els.interactionChannel.value='whatsapp';q.els.interactionType.value='follow_up';q.els.interactionStaff.value='JPG';q.els.interactionFollowup.checked=true;q.els.interactionFollowupAt.value='2026-10-09T09:00';node('nextActionInput').value='Follow up on quote';const calls=[];let message='';q.setMocks({api:async(action,data)=>{calls.push([action,data]);return {ok:true};},toast:text=>message=text});await q.saveInteraction();assert.deepEqual(calls.map(c=>c[0]),['create_interaction','update_inquiry']);assert.equal(calls[1][1].record.followup_date,'2026-10-09');assert.equal(calls[1][1].record.next_action,'Follow up on quote');assert.equal(calls[1][1].record.product_selected,row.product_selected);assert.match(message,/next step saved/);q.setMocks({api:async action=>{if(action==='update_inquiry')throw new Error('Temporary failure');return {ok:true};},toast:text=>message=text});await q.saveInteraction();assert.match(message,/Interaction saved; next step update failed/);assert.equal(q.els.saveInteractionBtn.disabled,false);});

test('existing booked guests get separate two-day reminders without changing manual tasks',()=>{const booking={...row,requested_date:'2026-11-30',tour_items_json:'',followup_date:'2026-09-25',next_action:'Collect remaining payment'};const reminder=q.preTourReminder(booking,'2026-10-06');assert.equal(reminder.date,'2026-11-28');assert.equal(reminder.kind,'scheduled');assert.equal(booking.followup_date,'2026-09-25');assert.equal(booking.next_action,'Collect remaining payment');assert.equal(q.preTourReminder({...booking,requested_date:'2026-12-03'},'2026-10-06').date,'2026-12-01');});
test('reminders use first booked service, flag late bookings and suppress closed/past trips',()=>{const booking={...row,tour_items_json:JSON.stringify([{tour:'Night Walk',product_selected:'MBW016',date:'2026-10-08',status:'booked'},{tour:'Birdwatching',product_selected:'MBW005',date:'2026-10-09',status:'booked'},{tour:'Other',date:'2026-10-07',status:'cancelled'}])};assert.equal(q.preTourReminder(booking,'2026-10-06').date,'2026-10-06');assert.equal(q.preTourReminder(booking,'2026-10-07').kind,'ready');assert.equal(q.preTourReminder(booking,'2026-10-09').kind,'past');assert.equal(q.preTourReminder({...booking,status:'completed'},'2026-10-06'),null);assert.equal(q.preTourReminder({...booking,is_archived:'Yes'},'2026-10-06'),null);assert.equal(q.preTourReminder({...booking,tour_items_json:'',requested_date:''},'2026-10-06').kind,'missing');});

test('fixed tour presets satisfy timing readiness, flexible services need no fixed time',()=>{q.state.allAssignments=[];const booking={...row,requested_date:'2099-11-30',guest_count:'1',tour_items_json:'',phone_number:'+593991234567',pickup_location:'Mindo Park'};assert.equal(q.reminderReadiness(booking).ready,true);assert.equal(q.reminderReadiness({...booking,pickup_location:'TBA'}).ready,false);assert.equal(q.reminderReadiness({...booking,phone_number:'',phone_raw:''}).ready,false);});
test('confirmation tracking uses exact inquiry itinerary, preserves sent outcomes and excludes deleted events',()=>{q.state.allAssignments=[];const key=q.reminderDeliveryKey(row);const event=(status,at)=>({inquiry_id:row.inquiry_id,occurred_at:at,note:'[MBW_PRETOUR] '+JSON.stringify({version:1,key,status})});assert.equal(q.reminderDeliveryState(row,[]).status,'pending');assert.equal(q.reminderDeliveryState(row,[event('failed','2026-10-06T09:00:00Z')]).status,'failed');const sent=event('sent','2026-10-06T10:00:00Z');assert.equal(q.reminderDeliveryState(row,[sent,event('failed','2026-10-06T11:00:00Z')]).status,'sent');assert.equal(q.reminderDeliveryState(row,[{...sent,is_deleted:'Yes'}]).status,'pending');assert.equal(q.reminderDeliveryState({...row,pickup_location:'Different pickup',tour_items_json:''},[sent]).status,'pending');assert.equal(q.reminderDeliveryState(row,[{...sent,inquiry_id:'other'}]).status,'pending');});
test('dashboard task counts use eligibility and sales versus trip definitions',()=>{q.state.records=[{...row,requested_date:'2099-01-01',tour_items_json:''},{...row,inquiry_id:'sales',status:'quoted',requested_date:'2099-01-01',tour_items_json:''},{...row,inquiry_id:'past',requested_date:'2020-01-01',tour_items_json:''},{...row,inquiry_id:'closed',status:'completed'}];q.renderActionCounts();assert.equal(node('salesDueCount').textContent,1);assert.equal(node('tripDueCount').textContent,1);});

test('booking review flags missing service dates and past Booked records only',()=>{assert.equal(q.bookingReviewIssues({...row,requested_date:'2020-01-01',tour_items_json:''})[0],'Past tour still Booked');assert.equal(q.bookingReviewIssues({...row,requested_date:'',tour_items_json:''})[0],'Service date missing');assert.equal(q.bookingReviewIssues({...row,status:'completed'}).length,0);assert.equal(q.bookingReviewIssues({...row,requested_date:'2099-01-01',tour_items_json:''}).length,0);});
test('timeline hides confirmation metadata behind a readable outcome',()=>{assert.match(q.interactionDisplayNote({note:'[MBW_PRETOUR] '+JSON.stringify({status:'sent',key:'private metadata'})}),/recorded as sent/);assert.doesNotMatch(q.interactionDisplayNote({note:'[MBW_PRETOUR] '+JSON.stringify({status:'failed',key:'private metadata'})}),/private metadata/);});

test('approved product schedules are specific and other services are flexible',()=>{for(const [code,start,end]of [['MBW004','06:00','09:00'],['MBW005','05:00','10:00'],['MBW006','05:00','15:00'],['MBW016','19:00','21:00']]){assert.equal(q.productSchedule(code).start_time,start);assert.equal(q.productSchedule(code).end_time,end);}assert.equal(q.productSchedule('ACT017').schedule_mode,'flexible');assert.equal(q.productSchedule('MBW007').start_time,'');});
test('service overrides and unknown existing metadata survive serialization',()=>{const item={id:'keep',tour:'Night Walk',product_selected:'MBW016',date:'2099-01-01',start_time:'18:30',end_time:'20:30',schedule_mode:'fixed',schedule_overridden:true,inherit_date:false,dropoff_location:'Quito airport',trip_direction:'return',custom_provider_ref:'keep-me'};const normalized=q.normalizeTourItems({tour_items_json:q.serializeTourItems([item])})[0];assert.equal(normalized.start_time,'18:30');assert.equal(normalized.custom_provider_ref,'keep-me');assert.equal(normalized.inherit_date,false);assert.equal(normalized.trip_direction,'return');});
test('inherited dates, guests and pickup update but explicit overrides are preserved',()=>{const initial={date:'2099-01-01',guests:'2',pickup_location:'Mindo',inherit_date:true,inherit_guests:true,inherit_pickup:true};const defaults={date:'2099-01-02',guests:'3',pickup_location:'Hotel'};const moved=q.inheritServiceDefaults(initial,defaults);assert.equal(moved.date,defaults.date);assert.equal(moved.guests,'3');const overridden=q.inheritServiceDefaults({...initial,date:'2099-01-05',inherit_date:false,pickup_location:'Quito',inherit_pickup:false},defaults);assert.equal(overridden.date,'2099-01-05');assert.equal(overridden.pickup_location,'Quito');assert.equal(q.inheritServiceDefaults({date:''},defaults).date,defaults.date);});
test('WhatsApp preview covers all booked services and validates each service',()=>{q.state.allAssignments=[];const booking={...row,requested_date:'2099-10-09',phone_number:'+593991234567',pickup_location:'Mindo Park',tour_items_json:JSON.stringify([{id:'primary',tour:'Birdwatching',product_selected:'MBW005',date:'2099-10-09',guests:'2',status:'booked',pickup_location:'Mindo Park'},{id:'night',tour:'Night Walk',product_selected:'MBW016',date:'2099-10-09',guests:'2',status:'booked',pickup_location:'Mindo Park'},{id:'bike',tour:'Mountain Biking',product_selected:'ACT017',date:'2099-10-10',guests:'2',status:'booked',pickup_location:'Mindo Park'}])};const model=q.confirmationModel(booking);assert.equal(model.ready,true);assert.match(model.message,/5:00/);assert.match(model.message,/7:00/);assert.match(model.message,/Flexible/);assert.match(model.message,/Ecuador/);const items=JSON.parse(booking.tour_items_json);items[1].pickup_location='TBA';assert.ok(q.confirmationModel({...booking,tour_items_json:JSON.stringify(items)}).missing.some(text=>text.includes('Night Walk')));items[1].pickup_location='Mindo Park';items[0].schedule_mode='fixed';items[0].start_time='';assert.ok(q.confirmationModel({...booking,tour_items_json:JSON.stringify(items)}).missing.some(text=>text.includes('start / pickup')));});
test('quote acceptance is historical, inquiry-scoped and latest clear is respected',()=>{const booking={inquiry_id:'accept'};const event=(accepted_at,occurred_at)=>({inquiry_id:'accept',occurred_at,note:'[MBW_QUOTE_ACCEPTED] '+JSON.stringify({accepted_at})});assert.equal(q.quoteAcceptance(booking,[]),'');const first=event('2026-10-07T14:00:00Z','2026-10-07T14:00:00Z');assert.equal(q.quoteAcceptance(booking,[first]),'2026-10-07T14:00:00Z');assert.equal(q.quoteAcceptance(booking,[first,event('','2026-10-07T15:00:00Z')]),'');assert.equal(q.quoteAcceptance(booking,[{...first,inquiry_id:'other'}]),'');});
test('acceptance save is idempotent and dates remain in persisted history',async()=>{const input=node('quoteAcceptedAtInput');input.value='2026-10-07';input.dataset.dirty='true';const calls=[];const rows=[];q.setMocks({api:async(action,data)=>{calls.push(action);if(action==='list_interactions')return {records:rows};if(action==='create_interaction')rows.push({...data.interaction});return {ok:true};},toast(){}});await q.persistQuoteAcceptance({inquiry_id:'accept',guest_id:'guest'});assert.deepEqual(calls,['list_interactions','create_interaction','list_interactions']);assert.equal(q.quoteAcceptance({inquiry_id:'accept'},rows),input.value);input.dataset.dirty='true';calls.length=0;await q.persistQuoteAcceptance({inquiry_id:'accept',guest_id:'guest'});assert.deepEqual(calls,['list_interactions','list_interactions']);});

test('review feature is off by default and opt-in rendering leaves saved records unchanged',()=>{context.location.search='';q.state.records=[{...row,phone_number:'+593991234567',assigned_to:'JPG',pickup_location:'QA Lodge'}];q.state.selectedId=row.inquiry_id;const before=JSON.stringify(q.state.records);q.renderReview();assert.equal(node('reviewTab').hidden,true);assert.equal(node('guestReviewPanel').hidden,true);context.location.search='?crmReview=1';q.setReviewVerified(true);q.renderReview();assert.equal(node('reviewTab').hidden,false);assert.equal(node('guestReviewPanel').hidden,false);assert.match(node('reviewView').innerHTML,/Reminder preparation/);assert.match(node('guestReviewPanel').innerHTML,/Saved record/);assert.equal(JSON.stringify(q.state.records),before);context.location.search='';q.renderReview();assert.equal(node('reviewView').innerHTML,'');});

test('preview blocks API writes before network access',async()=>{context.window.MBW_CRM_READ_ONLY_PREVIEW=true;await assert.rejects(q.api('update_inquiry',{record:{inquiry_id:'qa'}}),/Read-only preview/);context.window.MBW_CRM_READ_ONLY_PREVIEW=false;});

test('remaining-service confirmation excludes earlier services while full itinerary stays intact',()=>{const now=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guayaquil'}).format(new Date());const booking={inquiry_id:'ongoing',status:'booked',full_name:'QA',phone_number:'+593991234567',guest_count:'2',product_selected:'MBW004',requested_date:now,pickup_location:'QA Lodge',tour_items_json:JSON.stringify([{id:'primary',product_selected:'MBW004',date:now,guests:'2',status:'booked',pickup_location:'QA Lodge'},{id:'earlier',product_selected:'MBW016',date:'2020-01-01',guests:'2',status:'booked',pickup_location:'TBA'}])};const before=JSON.stringify(booking);const remaining=q.confirmationModel(booking,[],true);assert.equal(remaining.ready,true);assert.equal(remaining.services.length,1);assert.doesNotMatch(remaining.message,/Night Walk/);assert.equal(q.confirmationModel(booking,[]).services.length,2);assert.equal(JSON.stringify(booking),before);});
