import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../admin/guest-crm/index.html',import.meta.url),'utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const CRM_API_DEFAULT'));
new Function(script);
const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{dataset:{},value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return[];}});return nodes.get(id);};
const context={URLSearchParams,URL,Date,Intl,console,setTimeout,clearTimeout,location:{search:'',hostname:'localhost'},localStorage:{getItem(){return null;},setItem(){}},document:{getElementById:node,addEventListener(){},querySelectorAll(){return [];}},window:{addEventListener(){},location:{search:''}}};
vm.createContext(context);
vm.runInContext(script.replace('    })();','    globalThis.qa={bookingReviewIssues,interactionDisplayNote,reminderDeliveryKey,reminderReadiness,reminderDeliveryState,renderActionCounts,preTourReminder,compareReminderDates,cache,saveInteraction,setMocks(mock){api=mock.api;loadGuestWorkspace=async()=>{};render=()=>{};saveLocalRecords=()=>{};showToast=mock.toast;upsert=record=>{state.records=state.records.map(r=>r.inquiry_id===record.inquiry_id?record:r);};clearInteractionForm=()=>{};},setReportRows(rows){filteredReportRows=()=>rows;},serviceVisual,productVisual,popularProductLabel,optionsHtml,calendarEntriesForRecord,reportServiceKey,serviceItemLabel,reportCsv,reportPlainText,followupEligible,isTripFollowup,compareFollowups,getFiltered,renderFollowupSummary,state,els};})();'),context);
const q=context.qa;for(const id of ['searchInput','inlineSearchInput','statusFilter','inlineStatusFilter','repFilter','inlineRepFilter','quoteFilter','paymentFilter','viewFilter','followupFilter','sortInput','sortDirectionInput','statFollowUp','reportRangeHint','reportTypeInput','reportStatusInput'])q.els[id]=node(id);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
const product='ACT017 - Mountain Biking';
const row={inquiry_id:'fixture-bike',full_name:'QA Guest',tour_type:'Birdwatching',tour_category:'Birdwatching',service_type:'Birdwatching',product_selected:'MBW005 - Dance of the Andean Cock-of-the-Rock',requested_date:'2099-10-08',followup_date:'2020-01-01',status:'booked',tour_items_json:JSON.stringify([{id:'1',tour:'Other Activity or Tour',product_selected:product,service_type:'Activity',date:'2099-10-08',guests:'1',status:'booked'}])};
test('additional biking uses its own product and remains an activity in reports',()=>{const entry=q.calendarEntriesForRecord(row)[0];assert.equal(entry.service_type,'Activity');assert.equal(q.serviceVisual(entry).icon,'🚵🏼');assert.equal(q.serviceVisual(entry).label,'Mountain biking');assert.equal(q.serviceVisual(entry).fullLabel,'Mountain Biking');assert.equal(q.reportServiceKey(entry),'other');assert.equal(q.serviceItemLabel(entry._calendar_item).label,'Mountain Biking');});
test('all catalog icons stay outside canonical option values and report names',()=>{for(const [code,icon] of [['MBW004','🐥'],['MBW005','🐓'],['MBW006','🦜'],['MBW016','🦉'],['ACT017','🚵🏼'],['ACCOM01','🏨'],['TRANS03','🚘'],['MBW007','🐦'],['OSO002','🐻']]){assert.equal(q.productVisual(code)[0],icon);const canonical=code+' - Example';assert.ok(q.popularProductLabel(canonical).startsWith(icon+' '));assert.match(q.optionsHtml([canonical],canonical),new RegExp('value="'+canonical+'"'));assert.doesNotMatch(q.serviceVisual({product_selected:canonical}).fullLabel,/\p{Extended_Pictographic}/u);}});
test('due counts use the same eligibility as the queue and sales/trip queues partition it',()=>{q.state.records=[row,{...row,inquiry_id:'sales',status:'quoted',tour_items_json:'',product_selected:'MBW006',payment_status:'unpaid'},{...row,inquiry_id:'past',requested_date:'2020-01-01',tour_items_json:''},{...row,inquiry_id:'closed',status:'completed'},{...row,inquiry_id:'archived',is_archived:'Yes'},{...row,inquiry_id:'today',followup_date:today}];q.els.viewFilter.value='followups';q.els.sortInput.value='followup_date';q.els.sortDirectionInput.value='asc';const all=q.getFiltered();assert.equal(all.length,3);q.renderFollowupSummary();assert.ok(q.els.statFollowUp.innerHTML.startsWith('3'));q.els.viewFilter.value='salesFollowups';assert.equal(q.getFiltered().length,1);q.els.viewFilter.value='tripFollowups';assert.equal(q.getFiltered().length,2);assert.equal(all.at(-1).inquiry_id,'today');});
test('missing next step identifies missing date or owner or purpose without closed rows',()=>{q.state.records=[{...row,assigned_to:'JPG',next_action:'Confirm pickup'},{...row,inquiry_id:'missing',followup_date:''},{...row,inquiry_id:'closed',status:'completed'}];q.els.viewFilter.value='missingNextStep';assert.deepEqual(Array.from(q.getFiltered(),r=>r.inquiry_id),['missing']);});

test('CSV and copied report text contain plain product names with no display emojis',()=>{const entry=q.calendarEntriesForRecord(row)[0];q.setReportRows([{...entry,_report_date:'2099-10-08'}]);q.els.reportTypeInput.value='all';q.els.reportStatusInput.value='all';for(const output of [q.reportCsv(),q.reportPlainText()]){assert.match(output,/Mountain Biking/);assert.doesNotMatch(output,/\p{Extended_Pictographic}/u);assert.doesNotMatch(output,/Birding/);}});
test('logging follow-up saves history before updating the date and safely reports partial failure',async()=>{q.cache();q.state.records=[row];q.state.selectedId=row.inquiry_id;Object.assign(q.els.interactionNote,{value:'Outcome: guest requested more time'});q.els.interactionOccurredAt.value='2026-10-06T09:00';q.els.interactionDirection.value='outgoing';q.els.interactionChannel.value='whatsapp';q.els.interactionType.value='follow_up';q.els.interactionStaff.value='JPG';q.els.interactionFollowup.checked=true;q.els.interactionFollowupAt.value='2026-10-09T09:00';node('nextActionInput').value='Follow up on quote';const calls=[];let message='';q.setMocks({api:async(action,data)=>{calls.push([action,data]);return {ok:true};},toast:text=>message=text});await q.saveInteraction();assert.deepEqual(calls.map(c=>c[0]),['create_interaction','update_inquiry']);assert.equal(calls[1][1].record.followup_date,'2026-10-09');assert.equal(calls[1][1].record.next_action,'Follow up on quote');assert.equal(calls[1][1].record.product_selected,row.product_selected);assert.match(message,/next step saved/);q.setMocks({api:async action=>{if(action==='update_inquiry')throw new Error('Temporary failure');return {ok:true};},toast:text=>message=text});await q.saveInteraction();assert.match(message,/Interaction saved; next step update failed/);assert.equal(q.els.saveInteractionBtn.disabled,false);});

test('existing booked guests get separate two-day reminders without changing manual tasks',()=>{const booking={...row,requested_date:'2026-11-30',tour_items_json:'',followup_date:'2026-09-25',next_action:'Collect remaining payment'};const reminder=q.preTourReminder(booking,'2026-10-06');assert.equal(reminder.date,'2026-11-28');assert.equal(reminder.kind,'scheduled');assert.equal(booking.followup_date,'2026-09-25');assert.equal(booking.next_action,'Collect remaining payment');assert.equal(q.preTourReminder({...booking,requested_date:'2026-12-03'},'2026-10-06').date,'2026-12-01');});
test('reminders use first booked service, flag late bookings and suppress closed/past trips',()=>{const booking={...row,tour_items_json:JSON.stringify([{tour:'Night Walk',product_selected:'MBW016',date:'2026-10-08',status:'booked'},{tour:'Birdwatching',product_selected:'MBW005',date:'2026-10-09',status:'booked'},{tour:'Other',date:'2026-10-07',status:'cancelled'}])};assert.equal(q.preTourReminder(booking,'2026-10-06').date,'2026-10-06');assert.equal(q.preTourReminder(booking,'2026-10-07').kind,'ready');assert.equal(q.preTourReminder(booking,'2026-10-09').kind,'past');assert.equal(q.preTourReminder({...booking,status:'completed'},'2026-10-06'),null);assert.equal(q.preTourReminder({...booking,is_archived:'Yes'},'2026-10-06'),null);assert.equal(q.preTourReminder({...booking,tour_items_json:'',requested_date:''},'2026-10-06').kind,'missing');});

test('readiness requires phone, real meeting location and assigned start time',()=>{q.state.allAssignments=[];const booking={...row,requested_date:'2099-11-30',tour_items_json:'',phone_number:'+593991234567',pickup_location:'Mindo Park'};assert.deepEqual(Array.from(q.reminderReadiness(booking).missing),['Tour start time in assignments']);const assignments=[{inquiry_id:booking.inquiry_id,service_date:'2099-11-30',start_time:'06:00',assignment_status:'confirmed'}];assert.equal(q.reminderReadiness(booking,assignments).ready,true);assert.equal(q.reminderReadiness({...booking,pickup_location:'TBA'},assignments).ready,false);assert.equal(q.reminderReadiness({...booking,phone_number:'',phone_raw:''},assignments).ready,false);});
test('confirmation tracking uses exact inquiry itinerary, preserves sent outcomes and excludes deleted events',()=>{q.state.allAssignments=[];const key=q.reminderDeliveryKey(row);const event=(status,at)=>({inquiry_id:row.inquiry_id,occurred_at:at,note:'[MBW_PRETOUR] '+JSON.stringify({version:1,key,status})});assert.equal(q.reminderDeliveryState(row,[]).status,'pending');assert.equal(q.reminderDeliveryState(row,[event('failed','2026-10-06T09:00:00Z')]).status,'failed');const sent=event('sent','2026-10-06T10:00:00Z');assert.equal(q.reminderDeliveryState(row,[sent,event('failed','2026-10-06T11:00:00Z')]).status,'sent');assert.equal(q.reminderDeliveryState(row,[{...sent,is_deleted:'Yes'}]).status,'pending');assert.equal(q.reminderDeliveryState({...row,pickup_location:'Different pickup',tour_items_json:''},[sent]).status,'pending');assert.equal(q.reminderDeliveryState(row,[{...sent,inquiry_id:'other'}]).status,'pending');});
test('dashboard task counts use eligibility and sales versus trip definitions',()=>{q.state.records=[{...row,requested_date:'2099-01-01',tour_items_json:''},{...row,inquiry_id:'sales',status:'quoted',requested_date:'2099-01-01',tour_items_json:''},{...row,inquiry_id:'past',requested_date:'2020-01-01',tour_items_json:''},{...row,inquiry_id:'closed',status:'completed'}];q.renderActionCounts();assert.equal(node('salesDueCount').textContent,1);assert.equal(node('tripDueCount').textContent,1);});

test('booking review flags missing service dates and past Booked records only',()=>{assert.equal(q.bookingReviewIssues({...row,requested_date:'2020-01-01',tour_items_json:''})[0],'Past tour still Booked');assert.equal(q.bookingReviewIssues({...row,requested_date:'',tour_items_json:''})[0],'Service date missing');assert.equal(q.bookingReviewIssues({...row,status:'completed'}).length,0);assert.equal(q.bookingReviewIssues({...row,requested_date:'2099-01-01',tour_items_json:''}).length,0);});
test('timeline hides confirmation metadata behind a readable outcome',()=>{assert.match(q.interactionDisplayNote({note:'[MBW_PRETOUR] '+JSON.stringify({status:'sent',key:'private metadata'})}),/recorded as sent/);assert.doesNotMatch(q.interactionDisplayNote({note:'[MBW_PRETOUR] '+JSON.stringify({status:'failed',key:'private metadata'})}),/private metadata/);});
