import test from 'node:test';
import assert from 'node:assert/strict';
import {country, validDate, previousPeriod, extractRecords, aggregateGuests, guestStage, normalizeGA} from '../functions/lib/maps.mjs';
import {onRequestGet} from '../functions/api/maps.js';
const today='2026-10-02';
test('country aliases and unknowns are safe',()=>{assert.equal(country('USA').code,'US');assert.equal(country('United Kingdom').code,'GB');assert.equal(country('unknown').country,'Unknown country');assert.equal(country('<script>').country,'Unmapped country');});
test('dates reject invalid dates and oversized periods',()=>{assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2024-02-29'),true);assert.throws(()=>previousPeriod('2025-01-01','2026-10-02'));assert.deepEqual(previousPeriod('2026-09-01','2026-09-28'),{start:'2026-08-04',end:'2026-08-31'});});
test('past scheduled bookings are not assumed completed',()=>{assert.equal(guestStage({status:'booked',requested_date:'2026-09-01'},today),'overdue');assert.equal(guestStage({status:'completed'},today),'completed');assert.equal(guestStage({status:'booked',requested_date_start:'2026-10-01',requested_date_end:'2026-10-03'},today),'current');assert.equal(guestStage({status:'booked',requested_date:'2026-10-03'},today),'upcoming');assert.equal(guestStage({status:'booked'},today),'undated');assert.equal(guestStage({status:'quoted'},today),'prospects');});
test('cancelled, archived and duplicate-family records are excluded',()=>{for(const row of [{status:'cancelled'},{status:'duplicate'},{status:'booked',is_archived:'Yes'},{status:'completed',superseded_by_inquiry_id:'abc'}])assert.equal(guestStage(row,today),'excluded');});
test('guest aggregation removes repeated inquiries and never exposes PII',()=>{
 const rows=[{inquiry_id:'a',status:'completed',country:'US',guest_count:'2',email:'private@example.test',full_name:'Private name'},{inquiry_id:'a',status:'completed',country:'US',guest_count:'2'},{inquiry_id:'b',guest_id:'same',status:'completed',country:'USA',guest_count:'3'},{inquiry_id:'c',guest_id:'same',status:'completed',guest_count:'2 adults'}];
 const result=aggregateGuests(rows,{stage:'confirmed',today});assert.equal(result.duplicates,1);assert.equal(result.rows[0].records,2);assert.equal(result.rows[0].guests,5);assert.equal(result.missingGuestCounts,1);assert.ok(!JSON.stringify(result).includes('private@example.test'));assert.ok(!JSON.stringify(result).includes('Private name'));
});
test('date-filtered guest reports disclose undated exclusions',()=>{const result=aggregateGuests([{status:'completed',country:'CA'},{status:'completed',country:'US',requested_date:'2026-09-01'}],{stage:'completed',start:'2026-09-01',end:'2026-09-30',today});assert.equal(result.missingDates,1);assert.equal(result.rows.length,1);});
test('CRM incomplete and unexpected responses fail closed',()=>{assert.throws(()=>extractRecords({records:[],count:10}));assert.throws(()=>extractRecords({records:[],has_more:true}));assert.throws(()=>extractRecords({ok:false,records:[]}));assert.throws(()=>extractRecords({hello:'world'}));assert.deepEqual(extractRecords({records:[],count:0}),[]);});
const ga={ok:true,start:'2026-09-01',end:'2026-09-28',reports:{countries:{rows:[{country:'Canada',sessions:10,totalUsers:8,engagedSessions:5}],metadata:{timeZone:'America/Guayaquil'}}}};
test('GA territory labels remain distinct from unmapped groups',()=>{const report={...ga,reports:{countries:{rows:['Hong Kong','Macao','(not set)'].map(country=>({country,sessions:1,totalUsers:1,engagedSessions:0}))}}};assert.deepEqual(normalizeGA(report,ga.start,ga.end).rows.map(row=>row.code),['HK','MO','']);});
test('GA keeps available zero values but rejects missing metrics and wrong periods',()=>{const normalized=normalizeGA(ga,ga.start,ga.end);assert.equal(normalized.rows[0].engagementRate,.5);assert.throws(()=>normalizeGA(ga,'2026-08-01',ga.end));assert.throws(()=>normalizeGA({...ga,reports:{countries:{rows:[{country:'CA',sessions:1}]}}},ga.start,ga.end));assert.throws(()=>normalizeGA({...ga,reports:{countries:{...ga.reports.countries,truncated:true}}},ga.start,ga.end));});
test('public and preview hosts cannot expose reports',async()=>{for(const host of ['mindobirdwatching.com','mindobirdwatching-admin.pages.dev']){const response=await onRequestGet({request:new Request('https://'+host+'/api/maps?source=guests')});assert.equal(response.status,403);assert.equal(response.headers.get('cache-control'),'private, no-store');}});
test('admin reporting requires valid signed identity',async()=>{const response=await onRequestGet({request:new Request('https://admin.mindobirdwatching.com/api/maps?source=guests')});assert.equal(response.status,401);});
test('bad query parameters rejected before upstream requests',async()=>{for(const query of ['source=nope','source=guests&stage=bad','source=website&start=2026-02-30&end=2026-03-10']){const response=await onRequestGet({request:new Request('http://localhost/api/maps?'+query)});assert.equal(response.status,400);}});

test('same-season comparison retains equal days across leap years',()=>{assert.deepEqual(previousPeriod('2024-02-01','2024-02-29','year'),{start:'2023-01-31',end:'2023-02-28'});assert.deepEqual(previousPeriod('2026-09-04','2026-10-01','year'),{start:'2025-09-04',end:'2025-10-01'});assert.throws(()=>previousPeriod('2026-09-01','2026-09-30','bad'));});
