import test from 'node:test';
import assert from 'node:assert/strict';
import {opportunities,monthlyEvidence,reviewFilter} from '../admin/assets/js/market-decisions.mjs';
import {scoped} from '../admin/assets/js/market-model.mjs';
test('audience scopes retain unknown only worldwide and never mix Ecuador with international',()=>{const rows=[{code:'EC'},{code:'US'},{code:''}];assert.equal(scoped(rows).length,3);assert.deepEqual(scoped(rows,{audience:'domestic'}),[rows[0]]);assert.deepEqual(scoped(rows,{audience:'international'}),[rows[1]]);});
test('shortlist excludes low volume, prior-only and unknown markets; outcomes are country evidence',()=>{const rows=[{code:'US',country:'United States',sessions:30,engagementRate:.8,prior:{sessions:50}},{code:'EC',country:'Ecuador',sessions:40,engagementRate:.2,prior:{sessions:20}},{code:'CA',country:'Canada',sessions:19,engagementRate:1},{code:'',sessions:100,engagementRate:1}];const list=opportunities(rows,[{code:'US',confirmed:2,completedTours:3}]);assert.deepEqual(list.map(r=>r.code),['US','EC']);assert.equal(list[0].delta,-20);assert.deepEqual(list[0].reasons,['Strong engagement','Recorded bookings']);});
test('monthly evidence fills connected zero months but preserves absent comparison coverage',()=>{const rows=monthlyEvidence([{date:'2026-09-01',sessions:2},{date:'2026-09-03',sessions:3}],[{date:'2025-09-01',sessions:8}],[{date:'2026-09-03',completedTours:2}],[],{start:'2026-08-01',end:'2026-09-30',priorStart:'2025-08-01',priorEnd:'2025-09-30'});assert.equal(rows.length,2);assert.equal(rows[0].sessions,0);assert.equal(rows[0].priorCompleted,0);assert.equal(rows[1].sessions,5);assert.equal(rows[1].completed,2);assert.equal(rows[1].priorSessions,8);assert.equal(monthlyEvidence([{date:'2026-09-01',sessions:1}],[])[0].priorSessions,null);});
test('lodging queue uses current confirmed cohort, Ecuador timestamps, canonical countries and explicit unknown needs',()=>{const predicate=reviewFilter(new URLSearchParams({review:'lodging',start:'2026-09-01',end:'2026-09-30',market:'United States',audience:'international'}));const record={status:'completed',created_at:'2026-10-01T02:00:00Z',country:'USA',accommodation_needed:'maybe'};assert.equal(predicate(record),true);assert.equal(predicate({...record,accommodation_needed:'yes'}),false);assert.equal(predicate({...record,status:'quoted'}),false);assert.equal(predicate({...record,is_archived:'Yes'}),false);assert.equal(predicate({...record,country:'Ecuador'}),false);assert.equal(predicate({...record,created_at:'2026-10-01T06:00:00Z'}),false);assert.equal(reviewFilter(new URLSearchParams({review:'lodging',start:'2026-02-30',end:'2026-09-30'})),null);});

test('unavailable outcomes never become zero booking evidence',()=>{const rows=opportunities([{code:'US',country:'United States',sessions:25,engagementRate:.8}],[],false);assert.equal(rows[0].confirmed,null);assert.equal(rows[0].completedTours,null);assert.deepEqual(rows[0].reasons,['Growing interest','Strong engagement']);});
