import assert from 'node:assert/strict';import fs from 'node:fs';
const identity="const verifyIdentity=async token=>{if(token==='guide')return 'faustoandrade635@gmail.com';if(token!=='valid')throw Error();return 'admin';};";
const module=async file=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(file,'utf8').replace("import {verifyIdentity} from '../_middleware.js';",identity)).toString('base64'));
const {spikeRange,ranges,onRequestGet}=await module('functions/api/portfolio.js');assert.deepEqual(spikeRange('2026-10-01','2026-10-05','2026-10-05'),{start:'2026-10-01',end:'2026-10-05',priorStart:'2026-09-26',priorEnd:'2026-09-30'});for(const [a,b] of [['2026-10-06','2026-10-06'],['2026-06-01','2026-06-02'],['2026-09-20','2026-10-05'],['2026-09-31','2026-10-01'],['2026-10-05','2026-10-01']])assert.throws(()=>spikeRange(a,b,'2026-10-05'));
const end=ranges(28).end;let calls=[];globalThis.fetch=async(url,o)=>{assert(!url.includes('recorded-outcomes'));const q=JSON.parse(o.body);calls.push(q);return new Response(JSON.stringify({ok:true,version:3,...q,sites:[{domain:'mindobirdwatching.com',referrers:[]},{domain:'arguellodentistry.com',queries:[]}]}));};
const request=(extra='',token='valid')=>({request:new Request('https://admin.mindobirdwatching.com/api/portfolio?spike=1&site=arguellodentistry.com&from='+end+'&to='+end+extra,{headers:{'Cf-Access-Jwt-Assertion':token}})});
let p=await (await onRequestGet(request('&metric=sessions'))).json();assert(p.spike);assert.equal(p.sites.length,1);assert.equal(calls[0].domain,'arguellodentistry.com');assert.equal(calls[0].start,end);p=await (await onRequestGet(request('&metric=impressions'))).json();assert.equal(calls[1].domain,null);assert.equal(p.sites[0].domain,'arguellodentistry.com');assert.equal(p.comparison,'previous');assert.equal((await onRequestGet(request('&metric=bad'))).status,400);assert.equal((await onRequestGet(request('&inspect=1'))).status,400);assert.equal((await onRequestGet(request('','guide'))).status,403);assert.equal(calls.length,2);
const tracking=await module('functions/api/portfolio-tracking.js');assert.equal(tracking.validateTracking({domain:'arguellodentistry.com',startDate:'2026-10-01'}).startDate,'2026-10-01');for(const date of ['2026-09-31','2027-01-01','not-a-date'])assert.throws(()=>tracking.validateTracking({domain:'arguellodentistry.com',startDate:date}));assert.equal((await tracking.onRequest({request:new Request('https://admin.mindobirdwatching.com/api/portfolio-tracking',{method:'POST',headers:{'Cf-Access-Jwt-Assertion':'valid',Origin:'https://evil.test'}})})).status,403);
console.log('PASS: date/week bounds, exact prior periods, single-site response isolation, existing Google feed routes, no CRM read for spikes, guide denial and tracking-date validation');
