import test from 'node:test';import assert from 'node:assert/strict';import {reconcileBookings,reconciledDemand} from '../functions/lib/reconcile.mjs';import {aggregateDemand} from '../functions/lib/demand.mjs';
const options={today:'2026-10-03',start:'2026-09-01',end:'2026-09-30'};
const row=(extra={})=>({invoice_no:'100',guest_email:' A@Example.com ',home_country:'Spain',party_size:'2',tour_date:'2026-09-10',tour_completed:'Yes',service_type:'Birdwatching',...extra});
test('historical invoice lines and dates count one booking, preserve tour days and group size',()=>{const r=reconcileBookings([], [row(),row(),row({tour_date:'2026-09-11'})],options);assert.equal(r.records.length,1);assert.equal(r.records[0].completed_tour_days,2);assert.equal(r.records[0].guest_count,2);assert.equal(r.records[0].completed_date,'2026-09-11');});
test('email and tour date link historical booking to CRM, repeat trips stay separate',()=>{const crm=[{inquiry_id:'a',email:'a@example.com',country:'Spain',status:'completed',requested_date:'2026-09-10',created_at:'2026-09-02'},{inquiry_id:'b',email:'a@example.com',country:'Spain',status:'completed',requested_date:'2026-09-20'}];const r=reconcileBookings(crm,[row(),row({invoice_no:'101',tour_date:'2026-09-20'})],options);assert.equal(r.records.length,2);assert.equal(r.stats.matchedInvoiceBookings,2);const d=reconciledDemand(crm,r,aggregateDemand,options);assert.equal(d.rows[0].completedTours,2);assert.equal(d.rows[0].inquiries,1);assert.doesNotMatch(JSON.stringify(d),/a@example|invoice_no|inquiry_id/);});
test('ambiguous matches never add CRM copies to invoice total',()=>{const crm=['a','b'].map(inquiry_id=>({inquiry_id,email:'a@example.com',status:'completed',requested_date:'2026-09-10'}));const r=reconcileBookings(crm,[row()],options);assert.equal(r.records.length,1);assert.equal(r.stats.ambiguousMatches,1);});
test('IDs link without email; explicit invoice No overrides completed CRM',()=>{const r=reconcileBookings([{inquiry_id:'a',status:'completed',requested_date:'2026-09-10'}],[row({inquiry_id:'a',guest_email:'',tour_completed:'No'})],options);assert.equal(r.records.length,1);assert.equal(r.records[0].status,'booked');});
test('transport and reimbursement lines do not inflate tours; conflicting party sizes remain unknown',()=>{const r=reconcileBookings([],[row(),row({party_size:'3'}),row({product_selected:'TRANS01'}),row({invoice_no:'100-REIMB'})],options);assert.equal(r.records.length,1);assert.equal(r.records[0].guest_count,'');assert.equal(r.stats.excludedServiceRows,2);});
test('invalid invoice dates and conflicting countries are disclosed instead of guessed',()=>{const r=reconcileBookings([],[row(),row({tour_date:'bad',home_country:'Germany'})],options);assert.equal(r.records[0].completed_date,'');assert.equal(r.records[0].country,'Unknown country');assert.equal(r.stats.missingInvoiceDates,1);assert.equal(r.stats.countryConflicts,1);});
