// Intercept measurement requests: these QA visits do not reach GA4 or Meta.
const {chromium}=require('/Users/jpg/Tools/site-qa/node_modules/playwright');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true}),results=[];
for(const pathname of ['/','/quito-to-mindo-adventure-day-trip/','/es/excursion-aventura-quito-mindo/']){
 const context=await b.newContext(),page=await context.newPage(),events=[];
 await context.route(/google-analytics\.com\/.*collect/,route=>{const req=route.request(),query=new URL(req.url()).searchParams,body=req.postData()||'';const lines=body?body.split('\n'):[''];for(const line of lines){const fields=new URLSearchParams(line),name=fields.get('en')||query.get('en');if(name)events.push({name,path:new URL(fields.get('dl')||query.get('dl')||'https://mindobirdwatching.com/').pathname});}return route.fulfill({status:204});});
 await context.route(/facebook\.com|connect\.facebook\.net/,route=>route.abort());
 await context.route('**/assets/js/site.js*',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync('assets/js/site.js','utf8')}));
 if(pathname!=='/')await context.route('https://mindobirdwatching.com'+pathname,route=>route.fulfill({contentType:'text/html',body:fs.readFileSync('.'+pathname+'index.html','utf8')}));
 await page.goto('https://mindobirdwatching.com'+pathname);await page.waitForFunction(()=>window.__mbwGtmOwnsGa4===true,{timeout:15000});await page.waitForTimeout(1800);
 const native=events.filter(e=>e.name==='page_view');assert.equal(native.length,1,'Exactly one initial native page view: '+pathname);assert.equal(native[0].path,pathname);
 await page.locator('[data-mbw-consent="accept"]').click();await page.waitForTimeout(800);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await page.waitForTimeout(6000);assert.equal(events.filter(e=>e.name==='page_view').length,2,'History restoration emits one page view');
 await page.evaluate(()=>{const actual=Date.now;Date.now=()=>actual()+31*60*1000;window.dispatchEvent(new PointerEvent('pointerdown'));window.dispatchEvent(new PointerEvent('pointerdown'));});await page.waitForTimeout(6000);assert.equal(events.filter(e=>e.name==='page_view').length,3,'Idle return records one current-page view without duplicate clicks');results.push({pathname,initialPageViews:native.length,historyRestorePageViews:1,idleReturnPageViews:1,owner:'GTM'});await context.close();
}
const context=await b.newContext(),page=await context.newPage();await page.route('https://admin.mindobirdwatching.com/qa-tracking',route=>route.fulfill({contentType:'text/html',body:'<html><head><title>QA</title>'+['head.js','site.js','includes.js'].map(name=>'<script>'+fs.readFileSync('admin/assets/js/'+name,'utf8')+'</script>').join('')+'</head><body><script>'+fs.readFileSync('assets/js/site.js','utf8')+'</script></body></html>'}));await page.goto('https://admin.mindobirdwatching.com/qa-tracking');await page.waitForTimeout(3000);assert.equal(await page.locator('script[src*="googletagmanager"]').count(),0);results.push({host:'admin',trackingScripts:0});await context.close();await b.close();console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1)});
