import test from 'node:test';import assert from 'node:assert/strict';import {recommendResources,searchResources,validResource} from '../admin/assets/js/whatsapp-resources.mjs';
const target={id:'target',url:'https://mindobirdwatching.com/tours/target-bird-tour-builder/',title:'Target Bird Tour Builder',language:'en',type:'page',approved:true,available:true,topics:['target_birds']};
test('target bird inquiry offers verified curated link separately from reply',()=>{const messages=[{direction:'in',text:'Can you arrange three days of birding with specific target birds and lodging?'}],copy=structuredClone(messages);const result=recommendResources(messages,[target]);assert.equal(result[0].id,'target');assert.match(result[0].reason,/target birds/);assert.deepEqual(messages,copy);});
test('discovered, missing and unsafe resources are not automatically recommended',()=>{for(const changed of [{approved:false},{available:false},{url:'https://other.example/'},{type:'image'}])assert.equal(recommendResources([{direction:'in',text:'specific target birds'}],[{...target,...changed}]).length,0);assert.equal(validResource({...target,url:'javascript:alert(1)'}),false);});
test('page attribution is not a guest request and search is language aware',()=>{assert.equal(recommendResources([{direction:'in',text:'Hello\nPage: https://mindobirdwatching.com/target-birds/'}],[target]).length,0);assert.equal(searchResources([target],'bird builder','en').length,1);assert.equal(searchResources([target],'bird builder','es').length,0);});

test('Spanish resources are preferred and a new transport topic replaces old birding recommendations',()=>{const spanish={...target,id:'target-es',language:'es',url:'https://mindobirdwatching.com/es/tours/constructor-tour-aves-objetivo/'};assert.equal(recommendResources([{direction:'in',text:'Especies específicas'}],[target,spanish],'es')[0].id,'target-es');const transfer={...target,id:'transfer',topics:['transportation']};const result=recommendResources([{direction:'in',text:'specific target birds'},{direction:'in',text:'Actually I need transportation only'}],[target,transfer]);assert.deepEqual(result.map(r=>r.id),['transfer']);});

test('named reserve, activity and equipment queries retrieve classified knowledge pages',()=>{const pages=[{...target,id:'milpe',title:'Milpe Birding Reserve',url:'https://mindobirdwatching.com/birding-milpe/',category:'Reserves',keywords:['milpe'],topics:['reserves']},{...target,id:'chocolate',title:'Chocolate Tour',url:'https://mindobirdwatching.com/activities/chocolate-tour/',category:'Activities',keywords:['chocolate tour'],topics:['activities']},{...target,id:'equipment',title:'Birdwatching Equipment',url:'https://mindobirdwatching.com/birdwatching-equipment-binoculars-scopes/',category:'Equipment',keywords:[],topics:['equipment']}];for(const [text,id]of [['Can we visit Milpe?','milpe'],['Do you offer a chocolate tour?','chocolate'],['What binoculars should I bring?','equipment']])assert.equal(recommendResources([{direction:'in',text}],pages)[0].id,id);});
