const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path');
(async()=>{const root=process.cwd();const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const results=[];
for(const width of [360,390,768,1024,1440]){const page=await browser.newPage({viewport:{width,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/whatsapp')return route.fulfill({json:{knowledge:{status:'connected',checkedAt:new Date().toISOString(),items:[{id:'jewels',title:'Jewels of the Morning Forest',language:'en',subject:'Tours',text:'Jewels: $60 per person. Confirm availability.',shortText:'Jewels: $60 per person. Confirm availability.',longText:'Jewels: $60 per person. Detailed inclusions.',price:'$60/person',updated:'2026-10-05'}]}}});let file=u.pathname==='/whatsapp/'?'admin/whatsapp/index.html':u.pathname.startsWith('/assets/')?'admin'+u.pathname:u.pathname.slice(1);const full=path.join(root,file);if(!fs.existsSync(full))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(full),contentType:file.endsWith('.css')?'text/css':/\.(js|mjs)$/.test(file)?'application/javascript':'text/html'});});
await page.goto('http://localhost/whatsapp/');await page.locator('[data-thread]').first().click();await page.locator('#reply').fill('Preserved draft');await page.locator('#open-references').click();await page.locator('[data-knowledge][data-variant="long"]').click();if(!await page.locator('#reply').inputValue().then(v=>v.includes('Preserved draft')&&v.includes('Jewels:')))throw Error('Draft lost');
await page.locator('#sample-reply').click();if(!await page.locator('#messages').innerText().then(v=>v.includes('Preserved draft')))throw Error('Reply missing');
if(width<1200){await page.locator('#back-inbox').click();if(!await page.locator('.inbox').isVisible()||await page.locator('.chat').isVisible())throw Error('Mobile navigation failed');await page.locator('[data-thread]').first().click();}
await page.locator('#add-internal-note').click();await page.locator('#note').fill('Pickup pending');await page.locator('#save-note').click();await page.locator('[data-note-edit]').first().click();await page.locator('#note').fill('Pickup confirmed');await page.locator('#save-note').click();if(!await page.locator('#notes').innerText().then(t=>t.includes('Pickup confirmed')&&t.includes('edited by')))throw Error('Note edit failed');
await page.locator('#new-saved').click();await page.locator('#saved-form button').first().click();if(!await page.locator('#saved-error').isVisible())throw Error('Missing-field error invisible');
await page.locator('#saved-title').fill('Plain test reply');await page.locator('#saved-text').fill('A test reply costs $60');await page.locator('#saved-form button').first().click();if(!await page.locator('#saved-error').innerText().then(t=>t.includes('live reference')))throw Error('Price validation invisible');
await page.locator('#saved-text').fill('Hello, how can we help?');await page.locator('#saved-search').fill('No matching title');await page.locator('#saved-form button').first().click();if(await page.locator('#saved-search').inputValue()!=='')throw Error('Saved reply hidden by filter');if(!await page.locator('#saved-list').innerText().then(t=>t.includes('Plain test reply')))throw Error('Plain save missing');await page.reload();await page.locator('.mobile-tabs [data-pane="context"]').evaluate(b=>b.click());if(!await page.locator('#saved-list').innerText().then(t=>t.includes('Plain test reply')))throw Error('Plain save lost after reload');page.once('dialog',d=>d.accept());await page.locator('[data-saved-delete]').click();await page.locator('#add-internal-note').evaluate(b=>b.click());
await page.locator('#new-saved').click();await page.locator('#saved-title').fill('Tour details');await page.locator('#saved-text').fill('Hello {{guest_name}}');await page.locator('#saved-source').selectOption('jewels');await page.locator('#saved-variant').selectOption('long');await page.locator('#saved-text').fill('Hello {{guest_name}}, we can help you plan this tour.');await page.locator('#saved-form button').first().click();await page.locator('[data-saved-edit]').click();await page.locator('#saved-title').fill('Tour details updated');await page.locator('#saved-form button').first().click();await page.screenshot({path:'/tmp/mbw-whatsapp-library-'+width+'.png',fullPage:true});await page.locator('[data-saved-insert]').click();if(!await page.locator('#reply').inputValue().then(t=>t.includes('Hello Alex')&&t.includes('Detailed inclusions')))throw Error('Saved insertion failed');
await page.reload();await page.locator('.mobile-tabs [data-pane="context"]').evaluate(b=>b.click());if(!await page.locator('#saved-list').innerText().then(t=>t.includes('Tour details updated')))throw Error('Persistence failed');page.on('dialog',d=>d.accept());await page.locator('#notes-section summary').click();await page.locator('[data-note-delete]').first().click();if(await page.locator('[data-note-delete]').count())throw Error('Note delete failed');await page.locator('[data-saved-delete]').click();if(await page.locator('[data-saved-delete]').count())throw Error('Reply delete failed');
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow||errors.length)throw Error(JSON.stringify({width,overflow,errors}));
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/mbw-whatsapp-'+width+'.png',fullPage:true});results.push({width,overflow,errors,draftAndReply:'passed',navigation:'passed'});await page.close();}
console.log(JSON.stringify(results));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
