const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path');
(async()=>{const root=process.cwd();const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const results=[];
for(const width of [360,390,768,1024,1440]){const page=await browser.newPage({viewport:{width,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/inquiry-studio/api/session')return route.fulfill({json:{token:'local-test-token'}});if(u.pathname==='/inquiry-studio/api/whatsapp-suggest'){const body=route.request().postDataJSON();if(body.messages.some(m=>m.kind||m.note)||body.internal_notes)throw Error('Private notes in model request');return route.fulfill({json:{ok:true,reply:'Hello! What date are you considering?',sendingEnabled:false}});}if(u.pathname==='/api/whatsapp/reference')return route.fulfill({json:{ok:true,reference:'ci_test1234',attribution:{contact_intent_id:'ci_test1234',utm_source:'meta',utm_medium:'paid_social',utm_campaign:'booking_test'},checkedAt:new Date().toISOString(),readOnly:true}});if(u.pathname==='/api/whatsapp/crm'){const b=route.request().postDataJSON();if(b.inquiryId==='MISSING')return route.fulfill({json:{ok:true,records:[],checkedAt:new Date().toISOString()}});return route.fulfill({json:{ok:true,records:[{inquiryId:'INQ-TEST-001',name:'Fictional CRM Guest',tour:'Jewels',date:'2026-11-01',guests:'2',status:'booked',payment:'unpaid',pickup:'Test hotel',assignedTo:'Juan',items:[{tour:'Night Walk',date:'2026-11-01',status:'quoted'}]}],checkedAt:new Date().toISOString(),readOnly:true}});}if(u.pathname==='/api/whatsapp')return route.fulfill({json:{knowledge:{status:'connected',checkedAt:new Date().toISOString(),items:[{id:'jewels',title:'Jewels of the Morning Forest',language:'en',subject:'Tours',text:'Jewels: $60 per person. Confirm availability.',shortText:'Jewels: $60 per person. Confirm availability.',longText:'Jewels: $60 per person. Detailed inclusions.',price:'$60/person',updated:'2026-10-05'}]}}});let file=u.pathname==='/whatsapp/'?'admin/whatsapp/index.html':u.pathname.startsWith('/assets/')?'admin'+u.pathname:u.pathname.slice(1);const full=path.join(root,file);if(!fs.existsSync(full))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(full),contentType:file.endsWith('.css')?'text/css':/\.(js|mjs)$/.test(file)?'application/javascript':'text/html'});});
await page.goto('http://localhost/whatsapp/');await page.locator('[data-thread]').first().click();await page.locator('#reply').fill('Preserved draft');await page.locator('#open-references').click();await page.locator('[data-knowledge][data-variant="long"]').click();if(!await page.locator('#reply').inputValue().then(v=>v.includes('Preserved draft')&&v.includes('Jewels:')))throw Error('Draft lost');
await page.locator('#sample-reply').click();if(!await page.locator('#messages').innerText().then(v=>v.includes('Preserved draft')))throw Error('Reply missing');
if(width<1200){await page.locator('#back-inbox').click();if(!await page.locator('.inbox').isVisible()||await page.locator('.chat').isVisible())throw Error('Mobile navigation failed');await page.locator('[data-thread]').first().click();}
await page.locator('#add-internal-note').click();await page.locator('#note').fill('Pickup pending');await page.locator('#save-note').click();await page.locator('[data-note-edit]').first().click();await page.locator('#note').fill('Pickup confirmed');await page.locator('#save-note').click();if(!await page.locator('#notes').innerText().then(t=>t.includes('Pickup confirmed')&&t.includes('edited by')))throw Error('Note edit failed');
await page.locator('#new-saved').click();await page.locator('#saved-form button').first().click();if(!await page.locator('#saved-error').isVisible())throw Error('Missing-field error invisible');
await page.locator('#saved-title').fill('Plain test reply');await page.locator('#saved-text').fill('A test reply costs $60');await page.locator('#saved-form button').first().click();if(!await page.locator('#saved-error').innerText().then(t=>t.includes('live reference')))throw Error('Price validation invisible');
await page.locator('#saved-text').fill('Hello, how can we help?');await page.locator('#saved-search').fill('No matching title');await page.locator('#saved-form button').first().click();if(await page.locator('#saved-search').inputValue()!=='')throw Error('Saved reply hidden by filter');if(!await page.locator('#saved-list').innerText().then(t=>t.includes('Plain test reply')))throw Error('Plain save missing');await page.reload();await page.locator('.mobile-tabs [data-pane="context"]').evaluate(b=>b.click());if(!await page.locator('#saved-list').innerText().then(t=>t.includes('Plain test reply')))throw Error('Plain save lost after reload');page.once('dialog',d=>d.accept());await page.locator('[data-saved-delete]').click();await page.locator('#add-internal-note').evaluate(b=>b.click());
await page.locator('#new-saved').click();await page.locator('#saved-title').fill('Tour details');await page.locator('#saved-text').fill('Hello {{guest_name}}');await page.locator('#saved-source').selectOption('jewels');await page.locator('#saved-variant').selectOption('long');await page.locator('#saved-text').fill('Hello {{guest_name}}, we can help you plan this tour.');await page.locator('#saved-form button').first().click();await page.locator('[data-saved-edit]').click();await page.locator('#saved-title').fill('Tour details updated');await page.locator('#saved-form button').first().click();await page.screenshot({path:'/tmp/mbw-whatsapp-library-'+width+'.png',fullPage:true});await page.locator('[data-saved-insert]').click();if(!await page.locator('#reply').inputValue().then(t=>t.includes('Hello Alex')&&t.includes('Detailed inclusions')))throw Error('Saved insertion failed');
await page.reload();await page.locator('.mobile-tabs [data-pane="context"]').evaluate(b=>b.click());if(!await page.locator('#saved-list').innerText().then(t=>t.includes('Tour details updated')))throw Error('Persistence failed');page.on('dialog',d=>d.accept());await page.locator('#notes-section summary').click();await page.locator('[data-note-delete]').first().click();if(await page.locator('[data-note-delete]').count())throw Error('Note delete failed');await page.locator('[data-saved-delete]').click();if(await page.locator('[data-saved-delete]').count())throw Error('Reply delete failed');
await page.locator('.mobile-tabs [data-pane="chat"]').evaluate(b=>b.click());await page.locator('.suggest-tools summary').click();await page.locator('#reply').fill('My manual draft');const messageCount=await page.locator('#messages .bubble').count();await page.locator('#suggest-reply').click();await page.locator('#suggest-preview').waitFor({state:'visible'});if(await page.locator('#reply').inputValue()!=='My manual draft')throw Error('Suggestion overwrote draft');await page.locator('#use-suggestion').click();if(!await page.locator('#reply').inputValue().then(t=>t.includes('My manual draft')&&t.includes('What date')))throw Error('Suggestion insertion failed');if(await page.locator('#messages .bubble').count()!==messageCount)throw Error('Suggestion sent a message');
await page.locator('#open-crm-context').click();await page.locator('#crm-query').fill('Fictional');await page.locator('#crm-search-button').click();await page.locator('[data-crm-result]').click();if(!await page.locator('#guest-context-fields').innerText().then(t=>t.includes('Jewels')&&t.includes('unpaid')&&t.includes('booked')))throw Error('CRM summary missing');if(!await page.locator('#crm-record-link').getAttribute('href').then(t=>t.includes('INQ-TEST-001')))throw Error('CRM handoff missing inquiry ID');await page.locator('.mobile-tabs [data-pane="chat"]').evaluate(b=>b.click());await page.screenshot({path:'/tmp/mbw-whatsapp-context-'+width+'.png',fullPage:true});await page.locator('#open-crm-context').click();await page.locator('#inquiry-id').fill('MISSING');await page.locator('#link-form button').click();await page.waitForFunction(()=>document.querySelector('#crm-state').textContent.includes('No exact record'));if(!await page.locator('#guest-context-state').innerText().then(t=>t.includes('Fictional CRM Guest')))throw Error('Failed lookup changed link');await page.locator('#crm-unlink').click();if(await page.locator('#guest-context-fields').innerText()!=='')throw Error('Unlink retained guest details');await page.locator('.mobile-tabs [data-pane="chat"]').evaluate(b=>b.click());
await page.locator('.inquiry-source > details > summary').click();await page.locator('#sample-incoming').fill('Hi! Reserve this tour.\n\nPage: https://mindobirdwatching.com/mindo-cloud-forest-tours/?utm_source=meta&utm_medium=paid_social&utm_campaign=booking_test&utm_content=video_v1&meta_campaign_id=123&meta_adset_id=456&meta_ad_id=789&fbclid=private-click-id\n\nReference: ci_test1234');const keptDraft=await page.locator('#reply').inputValue();await page.locator('#sample-incoming-form button').click();if(await page.locator('#reply').inputValue()!==keptDraft)throw Error('Incoming message lost draft');if(!await page.locator('#inquiry-source-fields').innerText().then(t=>t.includes('Meta paid social tracking')&&t.includes('ci_test1234')))throw Error('Source extraction missing');await page.locator('#verify-reference').click();await page.waitForFunction(()=>document.querySelector('#reference-state').textContent.includes('matched'));if(!await page.locator('#reference-details').innerText().then(t=>t.includes('Saved website attribution')))throw Error('Reference details missing');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/mbw-whatsapp-source-'+width+'.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow||errors.length)throw Error(JSON.stringify({width,overflow,errors}));
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/mbw-whatsapp-'+width+'.png',fullPage:true});results.push({width,overflow,errors,draftAndReply:'passed',navigation:'passed'});await page.close();}
console.log(JSON.stringify(results));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
