import {authorize} from './index.js';
import {extractRecords,summarize} from './crm.js';
import {validDate} from '../../../admin/assets/js/whatsapp-readiness.mjs';
const CRM='https://n8n.mindobirdwatching.com/webhook/mbw-crm-admin-api';
const respond=(status,data)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
export const FIELDS=['first_name','last_name','full_name','phone_number','email','country','source_type','assigned_to','status','followup_date','tour_type','guest_count','requested_date','service_type','product_selected','duration_preference','transportation_needed','pickup_location','priority','availability_status','grouping_preference','grouping_status','quoted_amount','payment_status','payment_method','invoice_no','date_paid'];
const enums={source_type:['manual_whatsapp','manual_email','site_book_tour','site_contact','telegram','other'],status:['new','contacted','planning','qualified','quoted','follow_up','deposit_pending','deposit_paid','payment_pending','booked','completed','cancelled','did_not_book'],payment_status:['unpaid','deposit_pending','deposit_paid','payment_pending','paid','refunded'],transportation_needed:['Unknown','Yes','No'],availability_status:['pending','available','unavailable','needs_check'],grouping_preference:['unknown','private_only','open_to_group'],grouping_status:['unmatched','candidate','invited','accepted']};
const dates=['followup_date','requested_date','date_paid'];
export async function revision(record){const ordered=Object.fromEntries(Object.keys(record).sort().map(k=>[k,record[k]]));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(ordered))))].map(v=>v.toString(16).padStart(2,'0')).join('');}
function items(record){try{const v=record.tour_items_json||record.tour_items||'[]';const a=Array.isArray(v)?v:JSON.parse(v);return Array.isArray(a)?a:[];}catch{throw Error('Existing tour items are unreadable; review in Guest CRM before saving.');}}
export function patchRecord(record,patch,actor,financialConfirmed=false,primaryIndex){
 if(!patch||typeof patch!=='object'||Array.isArray(patch))throw Error('Invalid edits');const next={...record};for(const [key,value]of Object.entries(patch)){if(!FIELDS.includes(key)||typeof value!=='string'||value.length>300)throw Error('Invalid field: '+key);const v=value.trim();if(enums[key]&&!enums[key].includes(v))throw Error('Invalid '+key);if(dates.includes(key)&&v&&!validDate(v))throw Error('Use a valid date');if(key==='guest_count'&&v&&!/^(?:[1-9]|[1-9]\d)$/.test(v))throw Error('Guests must be a whole number from 1 to 99');if(key==='quoted_amount'&&v&&!/^\d{1,7}$/.test(v))throw Error('Use whole dollars for the accepted quote');if(key==='email'&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw Error('Enter a valid email');if(key==='phone_number'&&v&&!/^\+?[\d ()-]{7,25}$/.test(v))throw Error('Enter an international phone number');if(key==='assigned_to'&&!['','JPG','SS'].includes(v))throw Error('Select Juan, Susana or Unassigned');if(['quoted_amount','payment_status','payment_method','invoice_no','date_paid'].includes(key)&&v!==String(record[key]||'')&&!financialConfirmed)throw Error('Confirm financial changes before saving');next[key]=v;}
 if('country'in patch)next.home_country=next.country;if('source_type'in patch)next.source_tab=next.source_type;if('phone_number'in patch){next.phone_raw=next.phone_number;next.phone_normalized=next.phone_number.replace(/\D/g,'');}if('email'in patch)next.email_normalized=next.email.toLowerCase();if('first_name'in patch||'last_name'in patch){if(!('full_name'in patch))next.full_name=[next.first_name,next.last_name].filter(Boolean).join(' ');}if('requested_date'in patch)next.requested_date_start=next.requested_date_end=next.requested_date_text=next.requested_date;if('guest_count'in patch)next.guest_count_text=next.guest_count;if('tour_type'in patch)next.tour_category=next.interest_category=next.tour_type;
 const all=items(record);const relevant=['tour_type','requested_date','guest_count','product_selected','duration_preference','pickup_location'];if(all.length&&relevant.some(k=>k in patch)){const selectedIndex=Number.isInteger(primaryIndex)&&primaryIndex>=0&&primaryIndex<all.length?primaryIndex:-1;const primary=selectedIndex>=0?selectedIndex:all.findIndex(i=>i.id==='primary'||i.product_selected&&i.product_selected===record.product_selected);if(all.length>1&&primary<0)throw Error('Select the primary tour in Guest CRM before changing its summary; additional tours are preserved.');const index=primary<0?0:primary,updated={...all[index]};for(const [key,dest]of [['tour_type','tour'],['requested_date','date'],['guest_count','guests'],['product_selected','product_selected'],['duration_preference','duration'],['pickup_location','pickup_location']])if(key in patch)updated[dest]=next[key];if('requested_date'in patch&&'tour_date'in updated)updated.tour_date=next.requested_date;all[index]=updated;next.tour_items=next.tour_items_json=JSON.stringify(all);}
 if('status'in patch&&next.status!==record.status){next.stage_changed_at=new Date().toISOString();if(next.status==='completed'){next.tour_completed='Yes';next.completed_date=next.requested_date||new Date().toISOString().slice(0,10);}else if(record.status==='completed'){next.tour_completed='No';next.completed_date='';}}
 if('quoted_amount'in patch)next.quoted_currency=next.quoted_amount?'USD':'';next.updated_at=new Date().toISOString();next.internal_notes=[record.internal_notes||'','WhatsApp CRM edit by '+actor+' · '+next.updated_at+' · fields: '+Object.keys(patch).join(', ')].filter(Boolean).join('\n');return next;
}
async function call(payload){const r=await fetch(CRM,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({payload:JSON.stringify(payload)}).toString(),signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('CRM request failed');const data=await r.json();if(data.ok===false||data.success===false)throw Error(data.error||'CRM rejected the request');return data;}
async function projection(record){return {inquiryId:record.inquiry_id,guestId:record.guest_id||'',reference:record.contact_intent_id||'',revision:await revision(record),fields:Object.fromEntries(FIELDS.map(k=>[k,String(record[k]??(k==='country'?record.home_country:'')??'')])),items:items(record).map(i=>({tour:i.tour||'',date:i.date||i.tour_date||'',guests:i.guests||'',status:i.status||''})),summary:summarize(record)};}
export async function onRequestPost({request}){const denied=await authorize(request);if(denied)return denied;if(request.headers.get('Origin')!==new URL(request.url).origin)return respond(403,{ok:false,error:'Open through the admin workspace'});try{const raw=await request.text();if(raw.length>15000)throw Error('Request too large');const b=JSON.parse(raw);if(!/^[A-Za-z0-9_-]{1,100}$/.test(b.inquiryId||''))throw Error('Link an existing inquiry first');const records=extractRecords(await call({action:'list_inquiries',filters:{}})),matches=records.filter(r=>r.inquiry_id===b.inquiryId);if(matches.length!==1)return respond(409,{ok:false,error:'The inquiry is missing or duplicated. Review in Guest CRM.'});const record=matches[0];if(b.action==='load')return respond(200,{ok:true,record:await projection(record),checkedAt:new Date().toISOString()});if(b.action!=='save'||b.confirmed!==true)throw Error('Explicit CRM save required');const actor=request.headers.get('X-MBW-Staff-Profile');if(!['Juan','Susana'].includes(actor))throw Error('Select your staff profile');if(b.revision!==await revision(record))return respond(409,{ok:false,error:'CRM record changed since you loaded it. Your edits remain unsaved; reload and review.'});const next=patchRecord(record,b.patch,actor,b.financialConfirmed,b.primaryIndex);await call({action:'update_inquiry',record:next,inquiry_row:next,expected_updated_at:record.updated_at||''});let verified;try{verified=extractRecords(await call({action:'list_inquiries',filters:{}})).find(r=>r.inquiry_id===b.inquiryId);}catch{}if(!verified||Object.keys(b.patch).some(k=>String(verified[k]||'')!==String(next[k]||'')))return respond(202,{ok:true,verified:false,error:'Save submitted but not verified. Refresh before retrying; do not duplicate the inquiry.'});return respond(200,{ok:true,verified:true,record:await projection(verified),checkedAt:new Date().toISOString()});}catch(error){return respond(400,{ok:false,error:error.message||'CRM unavailable. Keep your edits and refresh before retrying.'});}}
