import {authorize} from './index.js';import {verifyIdentity} from '../../_middleware.js';
import {sampleThreads,mutateSample,validateSavedReply} from '../../../admin/assets/js/whatsapp-model.mjs';
import {validateBooking} from '../../../admin/assets/js/whatsapp-readiness.mjs';
const reply=(status,body)=>Response.json(body,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
export const SCHEMA=[`CREATE TABLE IF NOT EXISTS wa_test_threads(id TEXT PRIMARY KEY, revision INTEGER NOT NULL DEFAULT 1, data TEXT NOT NULL, mutation TEXT)`,`CREATE TABLE IF NOT EXISTS wa_test_staff(email TEXT PRIMARY KEY, name TEXT NOT NULL, seen TEXT NOT NULL, thread_id TEXT, editing INTEGER DEFAULT 0)`,`CREATE TABLE IF NOT EXISTS wa_test_events(id TEXT PRIMARY KEY, thread_id TEXT, actor TEXT NOT NULL, action TEXT NOT NULL, at TEXT NOT NULL, data TEXT)`,`CREATE TABLE IF NOT EXISTS wa_test_learning(id TEXT NOT NULL, version INTEGER NOT NULL, actor TEXT NOT NULL, at TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(id,version))`,`CREATE TABLE IF NOT EXISTS wa_test_replies(id TEXT PRIMARY KEY, revision INTEGER NOT NULL DEFAULT 1, data TEXT NOT NULL)`];
async function identity(request,env){const u=new URL(request.url);if(['localhost','127.0.0.1'].includes(u.hostname))return env.LOCAL_TEST_IDENTITY||'local-test@localhost';return verifyIdentity(request.headers.get('Cf-Access-Jwt-Assertion'));}
const initialized=new WeakMap();
async function setupOnce(db){await db.batch(SCHEMA.map(sql=>db.prepare(sql)));for(const t of sampleThreads()){t.owner='';t.notes=[];await db.prepare('INSERT OR IGNORE INTO wa_test_threads(id,data) VALUES(?,?)').bind(t.id,JSON.stringify(t)).run();}}
async function setup(db){if(!initialized.has(db))initialized.set(db,setupOnce(db).catch(error=>{initialized.delete(db);throw error;}));return initialized.get(db);}
async function snapshot(db,email){const threads=await db.prepare('SELECT id,revision,data FROM wa_test_threads ORDER BY id').all(),staff=await db.prepare("SELECT * FROM wa_test_staff WHERE email IN ('Juan','Susana') ORDER BY name").all(),learning=await db.prepare('SELECT l.* FROM wa_test_learning l JOIN (SELECT id,MAX(version) v FROM wa_test_learning GROUP BY id) x ON x.id=l.id AND x.v=l.version ORDER BY l.at DESC LIMIT 200').all(),replies=await db.prepare('SELECT id,revision,data FROM wa_test_replies').all();return {ok:true,mode:'shared_test',sendingEnabled:false,metaConnected:false,serverNow:Date.now(),identity:email,threads:threads.results.map(r=>({...JSON.parse(r.data),revision:r.revision})),staff:staff.results,learning:learning.results.map(r=>({...JSON.parse(r.data),id:r.id,version:r.version,actor:r.actor,at:r.at})),replies:replies.results.map(r=>({...JSON.parse(r.data),revision:r.revision}))};}
export async function onRequest({request,env}){const denied=await authorize(request);if(denied)return denied;if(!env.MBW_ATTRIBUTION_DB)return reply(503,{ok:false,error:'Shared database binding is unavailable. Browser sample mode remains available.'});const db=env.MBW_ATTRIBUTION_DB;try{const account=await identity(request,env),email=request.headers.get('X-MBW-Staff-Profile');if(!['Juan','Susana'].includes(email))return reply(400,{ok:false,error:'Select Juan or Susana before opening the shared inbox.'});await setup(db);for(const name of ['Juan','Susana'])await db.prepare('INSERT OR IGNORE INTO wa_test_staff(email,name,seen) VALUES(?,?,?)').bind(name,name,'1970-01-01T00:00:00Z').run();await db.prepare('INSERT INTO wa_test_staff(email,name,seen) VALUES(?,?,?) ON CONFLICT(email) DO UPDATE SET seen=excluded.seen').bind(email,email.split('@')[0],new Date().toISOString()).run();if(request.method==='GET'){const url=new URL(request.url);if(url.searchParams.get('export')==='1'){const data=await snapshot(db,email),events=await db.prepare('SELECT * FROM wa_test_events ORDER BY at').all(),history=await db.prepare('SELECT * FROM wa_test_learning ORDER BY at').all();return reply(200,{...data,events:events.results,learningHistory:history.results,exportedAt:new Date().toISOString()});}return reply(200,await snapshot(db,email));}if(request.method!=='POST')return reply(405,{ok:false,error:'Unsupported method'});if(request.headers.get('Origin')!==new URL(request.url).origin)return reply(403,{ok:false,error:'Same-origin staff workspace required.'});const raw=await request.text();if(raw.length>25000)return reply(413,{ok:false,error:'Request too large'});const body=JSON.parse(raw),at=new Date().toISOString();
 if(body.action==='presence'){await db.prepare('UPDATE wa_test_staff SET thread_id=?,editing=?,seen=? WHERE email=?').bind(/^sample-[1-4]$/.test(body.threadId)?body.threadId:'',body.editing?1:0,at,email).run();return reply(200,{ok:true,sendingEnabled:false});}
 if(body.action==='save_reply'||body.action==='delete_reply'){const old=await db.prepare('SELECT revision,data FROM wa_test_replies WHERE id=?').bind(body.reply?.id||body.id||'').first();if(old&&old.revision!==body.revision)return reply(409,{ok:false,error:'Saved reply changed. Refresh before editing.'});if(body.action==='delete_reply'){if(old)await db.prepare('DELETE FROM wa_test_replies WHERE id=? AND revision=?').bind(body.id,body.revision).run();}else{const data={...validateSavedReply(body.reply),updatedBy:email,updatedAt:at};if(old){const result=await db.prepare('UPDATE wa_test_replies SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(data),data.id,body.revision).run();if(!result.meta.changes)return reply(409,{ok:false,error:'Saved reply changed.'});}else await db.prepare('INSERT INTO wa_test_replies(id,data) VALUES(?,?)').bind(data.id,JSON.stringify(data)).run();}await db.prepare('INSERT INTO wa_test_events(id,thread_id,actor,action,at,data) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),'',email,body.action,at,JSON.stringify({id:body.reply?.id||body.id,before:old?.data||null,after:body.action==='save_reply'?body.reply:null})).run();return reply(200,await snapshot(db,email));}
 if(body.action==='learning'){const lesson=body.lesson||{},scope=lesson.scope;if(!['conversation','tour_selection','transportation','payment','other'].includes(scope))throw Error('Choose a learning scope.');const guidance=String(lesson.guidance||'').trim(),reason=String(lesson.reason||'').trim(),original=String(lesson.original||'').slice(0,4000),edited=String(lesson.edited||'').slice(0,4000);if(!guidance||guidance.length>2000||reason.length>1000)throw Error('Provide guidance up to 2,000 characters.');if(scope!=='conversation'&&/(?:[$€£]|\bUSD\b|https?:\/\/|\S+@\S+|\+?\d[\d ()-]{8,}\d)/i.test(guidance))throw Error('Reusable guidance cannot contain fixed prices, links or contact details. Save those as conversation-only review.');const id=String(body.id||crypto.randomUUID());if(!/^[A-Za-z0-9_-]{1,100}$/.test(id))throw Error('Invalid lesson ID');const latest=await db.prepare('SELECT MAX(version) version FROM wa_test_learning WHERE id=?').bind(id).first();const version=latest?.version||0;if(version!==Number(body.version||0))return reply(409,{ok:false,error:'Guidance changed. Refresh before revising.'});const data={scope,guidance,reason,original,edited,active:lesson.active===true,threadId:body.threadId||'',approvedBy:lesson.active?email:'',status:lesson.active?'approved':'review_only'};await db.prepare('INSERT INTO wa_test_learning(id,version,actor,at,data) VALUES(?,?,?,?,?)').bind(id,version+1,email,at,JSON.stringify(data)).run();return reply(200,await snapshot(db,email));}
 const row=await db.prepare('SELECT revision,data FROM wa_test_threads WHERE id=?').bind(body.threadId||'').first();if(!row)return reply(404,{ok:false,error:'Test conversation not found.'});if(row.revision!==body.revision)return reply(409,{ok:false,error:'Conversation changed on another device. Refresh and review before retrying.'});let t=JSON.parse(row.data),action=body.action,change=body.change||{};const staff=(await db.prepare("SELECT email FROM wa_test_staff WHERE email IN ('Juan','Susana')").all()).results.map(s=>s.email);
 if(['draft','reply','suggestion'].includes(action)&&t.owner!==email)return reply(409,{ok:false,error:'Take over this conversation before preparing or saving its shared reply.'});
 if(action==='takeover')t=mutateSample(t,{type:'assign',owner:email},email,Date.now(),staff);
 else if(action==='draft'){if(typeof change.text!=='string'||change.text.length>4000)throw Error('Draft too long');t.draft=change.text;}
 else if(action==='booking'){t.booking={...validateBooking(change),confirmedBy:email,confirmedAt:at};}
 else if(action==='suggestion'){if(typeof change.text!=='string'||change.text.length>4000)throw Error('Suggestion too long');t.suggestion=change.text?{text:change.text,engine:String(change.engine||'reviewed'),at,actor:email,lastMessageId:t.messages.at(-1)?.id}:null;if(t.suggestion)t.lastSuggestion=t.suggestion;}
 else if(action==='reset')return reply(409,{ok:false,error:'Shared samples are not reset from an individual device. Use a new test message or export first.'});
 else {t=mutateSample(t,{...change,type:action},email,Date.now(),staff);if(['incoming','reply'].includes(action))t.suggestion=null;}
 const mutation=crypto.randomUUID();const results=await db.batch([db.prepare('UPDATE wa_test_threads SET data=?,revision=revision+1,mutation=? WHERE id=? AND revision=?').bind(JSON.stringify(t),mutation,t.id,body.revision),db.prepare('INSERT INTO wa_test_events(id,thread_id,actor,action,at,data) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM wa_test_threads WHERE id=? AND mutation=?)').bind(mutation,t.id,email,action,at,JSON.stringify({revision:body.revision+1,accessAccount:account}),t.id,mutation)]);if(!results[0].meta.changes)return reply(409,{ok:false,error:'Another staff member changed this conversation. Refresh before retrying.'});return reply(200,await snapshot(db,email));
 }catch(error){return reply(400,{ok:false,error:error.message||'Shared workspace unavailable',sendingEnabled:false});}}
