import {verifyIdentity} from '../_middleware.js';
const domains=['mindobirdwatching.com','thecloudforestretreat.com','experienceecuador.com','mindotours.com','chocoandinotours.com','experiencetheamazon.com','businessbuyingandselling.com','eyesondanang.com','arguellodentistry.com'];
const reply=(status,data)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
export function validateGoal(body){const {domain,metric,days,target}=body;if(!domains.includes(domain)||!['sessions','impressions','clicks','forms','inquiries','confirmed','completedTours'].includes(metric)||(!['sessions','impressions','clicks','forms'].includes(metric)&&domain!==domains[0])||![7,28,90].includes(days)||!Number.isSafeInteger(target)||target<1||target>100000000)throw Error('Choose a website, available metric, reporting window and positive whole-number target.');return {domain,metric,days,target};}
export async function onRequest({request,env}){
 const url=new URL(request.url);if(url.hostname!=='admin.mindobirdwatching.com')return reply(403,{ok:false,error:'Open through MBW Admin.'});try{if(await verifyIdentity(request.headers.get('Cf-Access-Jwt-Assertion'))==='faustoandrade635@gmail.com')return reply(403,{ok:false,error:'Administrator access required.'});}catch{return reply(401,{ok:false,error:'Sign in through MBW Admin.'});}
 if(!['GET','POST','DELETE'].includes(request.method))return reply(405,{ok:false,error:'Unsupported method.'});if(request.method!=='GET'&&request.headers.get('Origin')!==url.origin)return reply(403,{ok:false,error:'Same-origin request required.'});const db=env.MBW_PORTFOLIO_DB;if(!db)return reply(503,{ok:false,error:'Goal storage unavailable.'});
 try{await db.prepare('CREATE TABLE IF NOT EXISTS portfolio_goals (domain TEXT PRIMARY KEY, metric TEXT NOT NULL, days INTEGER NOT NULL, target INTEGER NOT NULL, updated_at TEXT NOT NULL)').run();if(request.method==='POST'){const raw=await request.text();if(raw.length>1000)return reply(413,{ok:false,error:'Request too long.'});let goal;try{goal=validateGoal(JSON.parse(raw));}catch(e){return reply(400,{ok:false,error:e.message});}await db.prepare('INSERT INTO portfolio_goals VALUES (?,?,?,?,?) ON CONFLICT(domain) DO UPDATE SET metric=excluded.metric,days=excluded.days,target=excluded.target,updated_at=excluded.updated_at').bind(goal.domain,goal.metric,goal.days,goal.target,new Date().toISOString()).run();}if(request.method==='DELETE'){const domain=url.searchParams.get('site');if(!domains.includes(domain))return reply(400,{ok:false,error:'Choose a website.'});await db.prepare('DELETE FROM portfolio_goals WHERE domain=?').bind(domain).run();}const rows=await db.prepare('SELECT domain,metric,days,target,updated_at FROM portfolio_goals').all();return reply(200,{ok:true,goals:rows.results});}catch{return reply(503,{ok:false,error:'Goal storage unavailable. No change confirmed saved.'});}
}
